---
- name: "Install Tmux"
  ansible.builtin.apt:
    name: tmux
    state: present
  become: true
  become_method: sudo

- name: "Copying Tmux Config"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/.tmux.conf"
    dest: "{{ ansible_env.HOME }}"
