---
- name: "Install Zsh"
  ansible.builtin.apt:
    name: zsh
    state: present
  tags:
    - zsh
    - never

- name: Set shell of {{ ansible_env.USER }} to `/bin/zsh`
  ansible.builtin.command: usermod --shell /bin/zsh {{ ansible_env.USER }}
  become: true
  changed_when: false
  tags:
    - zsh
    - never
